# Profile generation
This is an example of generating hourly electricity consumption for 150 random households(some with soalr power and some with wind power) in Belgium from July 1, 2020 to July 7, 2020.

* [Electricity Consumption Profile Generation](#ele_profile)
* [Windpower Turbine Profile Generation](#windpower_profile)
* [PV Profile Generation](#pv_profile)

## Electricity Consumption Profile Generation<a class="anchor" id="ele_profile"></a>
The load profile of electricity consumption was generated by using [loadprofilegenerator](https://www.loadprofilegenerator.de/) first as the raw data. As an example, there are 61 random family profile generated in the data file.

In [1]:
import csv
import os
import random

import pandas as pd

In [2]:
file_name = "\Results\SumProfiles_3600s.HH1.Electricity.csv"
dir_name = "data\\"

dirs = os.listdir(dir_name)
all_list = []
data=[]

for i in dirs:
    # print(i)
    File_Path = dir_name + i + file_name
    # print(File_Path)
    with open(File_Path) as f:
        raw = []
        f_csv = csv.reader(f)

        header = next(f_csv)

        for row in f_csv:
            x = str(row).split(";")
            raw.append(float(x[2][0:-2]))
    all_list.append(raw)
    
# to expand the data from 61 to 150, we choose a random constant
for i in range(150):
    randdata = random.choice(all_list)
    adata = [round((i * random.uniform(0.9, 1.1)), 2) for i in randdata]
    data.append(adata)

Originally, the data was expanded from 61 households, as an example, here are 10 households.

In [3]:
# In total, there are 150 households with 150 hours each.
df=pd.DataFrame(data).T
df

,0,1,2,3,4,5,6,7,8,9,...,140,141,142,143,144,145,146,147,148,149
0,0.06,0.08,0.11,0.06,0.32,0.11,0.04,0.02,0.13,0.19,...,0.03,0.02,0.07,0.07,0.09,0.03,0.06,0.06,0.08,0.09
1,0.04,0.08,0.11,0.06,0.15,0.17,0.04,0.03,0.10,0.07,...,0.03,0.03,0.07,0.11,0.04,0.03,0.12,0.11,0.16,0.09
2,0.05,0.11,0.10,0.09,0.18,0.12,0.05,0.02,0.09,0.05,...,0.07,0.03,0.07,0.13,0.05,0.07,0.21,0.21,0.09,0.08
3,0.06,0.15,0.19,0.16,0.20,0.11,0.09,0.03,0.13,0.06,...,0.12,0.03,0.15,0.07,0.04,0.11,0.06,0.06,0.08,0.09
4,0.04,0.23,0.21,0.12,0.25,0.12,0.04,0.03,0.11,0.10,...,0.43,0.03,0.07,0.06,0.09,0.38,0.07,0.06,0.08,0.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,0.06,0.93,2.84,0.26,4.51,0.23,0.67,1.60,0.50,0.28,...,1.80,1.60,0.14,0.30,1.02,1.78,2.37,2.26,0.29,1.38
164,0.09,0.13,1.26,0.40,2.86,0.86,0.87,0.17,0.29,0.47,...,0.54,0.20,0.27,0.78,0.53,0.54,0.34,0.36,0.45,0.86
165,0.05,1.25,0.19,0.32,1.35,0.35,0.12,0.49,0.26,0.43,...,0.55,0.59,0.56,0.71,0.43,0.57,0.33,0.38,2.31,0.40
166,0.05,0.35,0.12,0.22,0.48,0.15,0.07,0.22,0.17,0.20,...,0.20,0.23,0.08,0.36,0.34,0.21,0.31,0.30,0.15,0.20
167,0.05,0.13,0.09,0.15,0.30,0.10,0.04,0.04,0.08,0.06,...,0.03,0.04,0.08,0.15,0.12,0.03,0.06,0.06,0.14,0.09

There is already a file that generated 150 househoolds from 61 raw data.

In [4]:
# df.to_excel("ele_profile.xlsx", index=False)

## Windpower Turbine Profile Generation<a class="anchor" id="windpower_profile"></a>
The windpower profile can be found in another repository. You can click the [link](https://github.com/PeijieZ/WindpowerlibTurbine-model) to find more.
Here I built three raw data for prosumers that contain 1.0kw, 1.5kw and 2.0kw wind turbine. The data then expand to 10.

In [5]:
df1 = pd.read_excel("WT_0701-0707_raw.xlsx", usecols=[0])
df2 = pd.read_excel("WT_0701-0707_raw.xlsx", usecols=[1])
df3 = pd.read_excel("WT_0701-0707_raw.xlsx", usecols=[2])

raw = [df1[2.3].tolist(), df2[3.6].tolist(), df3[4.7].tolist()]
data = []


for i in range(10):
    randdata = random.choice(raw)
    adata = [round((i * random.uniform(0.8, 1.0))/1000, 2) for i in randdata]
    data.append(adata)

df4 = pd.DataFrame(data)
df = df4.T
# df.to_excel("WT profile.xlsx", index=False)
df

        0     1     2     3     4     5     6     7     8     9
0    0.76  0.26  0.28  0.68  0.48  0.33  0.51  0.29  0.50  0.53
1    0.72  0.31  0.31  0.67  0.48  0.31  0.56  0.32  0.56  0.47
2    0.70  0.30  0.26  0.70  0.48  0.25  0.43  0.29  0.50  0.43
3    0.72  0.26  0.24  0.67  0.44  0.26  0.51  0.25  0.50  0.51
4    0.73  0.31  0.25  0.64  0.45  0.25  0.54  0.26  0.55  0.55
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
163  0.35  0.05  0.04  0.40  0.14  0.05  0.13  0.04  0.12  0.13
164  0.34  0.07  0.06  0.40  0.16  0.06  0.16  0.07  0.16  0.15
165  0.51  0.15  0.12  0.49  0.27  0.13  0.28  0.15  0.28  0.31
166  0.50  0.14  0.13  0.53  0.27  0.15  0.28  0.14  0.29  0.26
167  0.45  0.14  0.14  0.52  0.25  0.14  0.27  0.15  0.30  0.29

[168 rows x 10 columns]

## PV Profile Generation<a class="anchor" id="pv_profile"></a>
The windpower profile can be found in another repository. You can click the [link](https://github.com/PeijieZ/WindpowerlibTurbine-model) to find more.
Here I built three raw data for prosumers that contain 1.0kw, 1.5kw and 2.0kw wind turbine. The data then expand to 10.